language: node_js

node_js:
  - 0.10

install : npm install
script  : npm start

branches:
  only:
    - master
    - stable

deploy:
  - provider: opsworks
    access_key_id:
      secure: TWlVI5XplLro661LbgXjyJNiMHsH9zN5nN4aEWycSYfXTzK0apxrs/x+nzV2YGN6jYtKJ41TJvU3V5UEkV0e0Vfn5ax46FMIOmuLgrbklKQroQb4B3GSMwjx9R0BLJisHa7cjOKf/Eu2+m0Gu2IvyxurdcYXbr6sXyhuaqysj4M=
    secret_access_key:
      secure: UfjUG++j4Hv3qa5hkVj54VURLV3NPCmVwv9+O0p2GaGNesE2eqNR1//pVrteuVrfgSOeHQDxOqi8xRdn1iIlhToBOXjcUjJ97vRfgcAiD16aL1j1wat21BMls7S5crhDakkf/jGhL/xNkYV0se8B3G0daRxydXPbHHsj2d70V+k=
    app-id: 573363bc-37cc-4c8a-993f-bf82d5edbea9
    on:
      repo: webRunes/Login-WRIO-App
  - provider: s3
    access_key_id:
      secure: E8UFms7+Xv7PxCT3kybFHGI44O2g9KehUdEkddQaYyxNYrQD9RQyHi7kMXO42kWUHzYeM3k5OAvJKpXj463amMMES4rxP1h557F1DBb5Z3DrA+4ubSsq/LlCNI8Dc80xZhgf1ZDs+b0Ld2AyxMcfB1Ca7fBcVVIGkq5zzqTQ9fg=
    secret_access_key:
      secure: iYeo/OGPNjMRkx+FIMtCRRHenR5cU+5p/JSFRIEtpyYo1PD68Hnlaornaj379RazR1IlV1Vmr6vlnvzjOOJIZeB36jQ5nvYgP2oicWiDlvm2VWSIQVR3ehLkk3wZnZ9yd1phM/QyCiSIQ5/PgUJm49owWjmquaeZbzwoxy39JsE=
    bucket: wrio
    upload-dir: Login-WRIO-App
    acl: public_read
    on:
      repo: webRunes/Login-WRIO-App
